# Generated by Django 4.2.6 on 2024-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_remove_product_quantity_cartproducts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproducts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Count'),
        ),
    ]
